### ISSUE TITLE
Something wrong with `vagrant reload`

### ISSUE THREAD

**Issue by ailispaw** [rancherio/os-vagrant#1] opened 2015-02-25 01:50 UTC
When I use `vagrant reload` after `vagrant up`, it can not establish a SSH connection within Vagrant and ssh by manually either.

I created some patches for RancherOS on Vagrant, it works fine except `vagrant reload`.
Vagrantfile including patches for RancherOS
https://gist.github.com/ailispaw/11034d3ea0ab4f46a249

**Comment by cloudnautique** [comment] 2015-02-25 05:47
My favorite kind of error.. intermittent. I am able to reproduce the behavior, but if I keep reloading I can get back in again. Will have to debug some more.

**Comment by ailispaw** [comment] 2015-02-25 06:32
Yes, the same behavior here.
I tried another `vagrant up & reload` and it works fine this time. But right after that, another `vagrant reload` doesn't.

**Comment by ailispaw** [comment] 2015-02-25 19:23
I created a box with the raw rancheros.iso for just testing. It works fine with password SSH method so far.
https://github.com/ailispaw/rancheros-iso-box/releases/tag/v0.1.0
I hope this would be helpful.

**Comment by cloudnautique** [comment] 2015-02-27 02:14
Thanks @ailispaw, I don't think it is related to SSH keys or passwords. When the box is unreachable the eth0 network interface is not present. I have to rerun udev and then initialize the network. Something wonky with Virtualbox. If you are interested, to enable the username/password login add:

`rancher.password=rancher` to the vmlinuz line in the grub.cfg when you boot up. This will let you login via console in Virtualbox.

To make it persistent mount up /dev/sda1 and add it to /boot/grub/grub.cfg.

**Comment by ailispaw** [comment] 2015-02-27 11:18
@cloudnautique Thank you for the explanation.
I created an another box which has SSH private key method using /opt/rancher/bin/start.sh.
https://github.com/ailispaw/rancheros-iso-box/releases/tag/v0.2.0
It works fine as well. It seems not to be related to SSH method, as you mentioned.

**Comment by dud3** [comment] 2015-02-27 22:33
Hi Guys I didn't wanted to open another issue but, running `vagrant up` I goes this as an output: 
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'rancheros' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'rancheros' (v0) for provider: virtualbox
    default: Downloading: http://cdn.rancher.io/vagrant/x86_64/prod/rancheros_virtualbox.box
==> default: Successfully added box 'rancheros' (v0) for 'virtualbox'!
==> default: Importing base box 'rancheros'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: os-vagrant_default_1425075946084_67945
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: rancher
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

Hopefully this is not a silly question or mistake of mine.

**Comment by cloudnautique** [comment] 2015-02-27 22:38
@dud3 you got this on an initial `vagrant up` ? Can you give more info on vagrant version/vbox version your using?

 We are using the insecure_private_key pair from Vagrant. We had issue #2 pop up and it appears to have been caused by having an older version of that key. Is that something that is possible with your setup?

**Comment by dud3** [comment] 2015-02-27 22:44
@cloudnautique Yes this was my initial `vagrant up`. 
I have: 
* Vagrant 1.7.2
* Vbox 4.3.10_Ubuntur93012

I might have the older version of that key, I'll try #2.

BTW: Sorry, I should have been checking the closed issues first.

**Comment by dud3** [comment] 2015-02-27 22:57
@cloudnautique I actually already had the new key, still the connection times out.

**Comment by stela5** [comment] 2015-03-10 17:05
@dud3 Which host OS are you using?  If Windows, did you run <code>vagrant up</code> with a privileged (admin) *PowerShell* terminal?  Also, you might try installing http://git-scm.com/download/win and choosing *Use Git and optional Unix tools from the Windows Command Prompt* when prompted during install.  Then open a new PowerShell terminal and retry.

**Comment by vdemario** [comment] 2015-03-11 21:14
I got this on my first `vagrant up` as well, just like @dud3 .

I'm on Linux Mint 17 with a freshly installed vagrant and virtualbox:

    Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux 
    Vagrant 1.7.2
    Virtualbox 4.3.24 r98716

Output from `vagrant up` follows:

    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Box 'rancheros' could not be found. Attempting to find and install...
        default: Box Provider: virtualbox
        default: Box Version: >= 0
    ==> default: Adding box 'rancheros' (v0) for provider: virtualbox
        default: Downloading: http://cdn.rancher.io/vagrant/x86_64/prod/rancheros_v0.1.2_virtualbox.box
    ==> default: Successfully added box 'rancheros' (v0) for 'virtualbox'!
    ==> default: Importing base box 'rancheros'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Setting the name of the VM: os-vagrant_default_1426106689309_67861
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
    ==> default: Forwarding ports...
        default: 22 => 2222 (adapter 1)
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2222
        default: SSH username: rancher
        default: SSH auth method: private key
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
    Timed out while waiting for the machine to boot. This means that
    Vagrant was unable to communicate with the guest machine within
    the configured ("config.vm.boot_timeout" value) time period.
    
    If you look above, you should be able to see the error(s) that
    Vagrant had when attempting to connect to the machine. These errors
    are usually good hints as to what may be wrong.
    
    If you're using a custom box, make sure that networking is properly
    working and you're able to connect to the machine. It is a common
    problem that networking isn't setup properly in these boxes.
    Verify that authentication configurations are also setup properly,
    as well.
    
    If the box appears to be booting properly, you may want to increase
    the timeout ("config.vm.boot_timeout") value.

I tried a `vagrant reload` and the same thing happens.

**Comment by sameedali** [comment] 2015-03-13 12:55
Hi 
I'm having the same issue with vagrant up i.e. the connection keeps getting timed out.
I'm on a x64 windows 8.1 using vagrant 1.7.2. Also Vagrant runs other boxes perfectly fine so I think the problem is not with the setup.
I have managed to get a ssh login prompt if i ssh to localhost at port 2222 however the VM does not approve of the credentials despite them being configured in the Vagrant File.

I look forward to resolving this issue. 
Any help is appreciated.

**Comment by cloudnautique** [comment] 2015-03-22 04:03
With the most recently refreshed box, we have not observed the failing to load NICs/no ssh issue on reload. Will keep this issue open for a bit to see what others experience.

**Comment by cloudnautique** [comment] 2015-03-22 04:19
@sameedali, do you mean that you use try to login using the insecure Vagrant key manually? I haven't had a chance to test personally with Windows. 

@sameedali @vdemario you can try refreshing and using the new Vagrantfile (which pulls in a newer version of RancherOS and configuration). We are now using VirtIO for the network drivers and cut the disks over to SATA. Perhaps there were issues with the intel 1000 nics in use on the 0.1.2 box. 

If you need to get into the VM to troubleshoot further try:
1. Enable vb_gui in the Vagrantfile.
2. At the Grub prompt press `e` to edit.
3. At the end of the line: 
`linux /boot/vmlinuz-<version>-rancheros`
add:
`rancher.password=rancher`
So it should look like
`linux /boot/vmlinuz-<version>-rancheros rancher.password=rancher`
where version is whatever version you are running.
Then press f10 to continue booting.

When it gets to the login prompt you should be able to login with u:rancher p:rancher
From there you will be on the console. Any troubleshooting or information you can provide to use would be helpful, and appreciated!

**Comment by ailispaw** [comment] 2015-03-22 13:44
Now `vagrant reload` works well for me.
But `vagrant up` takes long to wait for SSH Remote connection with private_network.
It looks trying DHCP for eth1 before executing the configure_networks monkey patch.

**Comment by cloudnautique** [comment] 2015-03-22 13:54
Doh, I have a fix for that. I'll get it added in the next day or so. Have you ever seen this issue 
https://github.com/mitchellh/vagrant/issues/5498

**Comment by ailispaw** [comment] 2015-03-22 14:01
@cloudnautique Yup.
I have experienced at https://github.com/ailispaw/rancheros-iso-box/issues/2 as well.
And patched here https://github.com/ailispaw/rancheros-iso-box/commit/e6d49c95cc887cf6eff39092379382327fe4b21d . It's ugly. :(

It seems to check guest_capability earlier than loading the monkey patch.

**Comment by ailispaw** [comment] 2015-03-22 14:09
If we have a guest plugin for RancherOS inside Vagrant, it should be gone.

**Comment by cloudnautique** [comment] 2015-03-23 19:13
@ailispaw pushed out box 0.2.1.1 that brings up only eth0 on DHCP so startup should be faster.

`vagrant box update` if you are running off our stuff.

**Comment by sameedali** [comment] 2015-03-23 21:22
Just checked it with updated rancher image.
Seems to be working fine now.
Thanks @cloudnautique

**Comment by ailispaw** [comment] 2015-03-23 22:43
@cloudnautique Thanks.
It seems the box v0.2.1.1 at atlas is not activated yet.

**Comment by cloudnautique** [comment] 2015-03-23 22:52
I went to atlas, and I see what you mean.. it says latest release is `0.2.1.`  

when I do vagrant up I'm seeing:
```

**Comment by ailispaw** [comment] 2015-03-23 23:05
@cloudnautique Sorry about that. I just saw the box at atlas on my cell phone at that time.
Now I can update the box and it works great. Thanks.

**Comment by imikushin** [comment] 2015-03-24 08:18
Great!
Would it make sense to specify exact current box version in Vagrantfile?
`vagrant up` would not spend time checking for updated box then. If new
version is released, it'd probably have to be specified in Vagrantfile
anyway.

**Comment by cloudnautique** [comment] 2015-03-24 17:20
@imikushin I am not opposed to the idea, here is the initial line of thinking...

 Now that we are versioning the boxes by default on `vagrant up` it checks for box updates and lets the user know. If it is a fresh(first time) `vagrant up` Vagrant automatically downloads the latest box to start out. There are also params in the Vagrantfile that can be added to turn the behavior on/off or to auto-update. Our initial approach is not forcing users to update at a specific time, leaving it to them to decide when the best time is.

Also, new in RancherOS v0.2.x is the `rancherctl os` commands that allow you to easily upgrade the OS.

That was a long way of saying, the thought was to only update this Vagrantfile when we change functionality with Vagrant or the box itself and let native Vagrant handle the rest for now, but we could update this file each time.

**Comment by cloudnautique** [comment] 2015-04-02 16:54
This issue has been quiet for a while now, @ailispaw would you consider it closed with the v0.2.1 release?

**Comment by ailispaw** [comment] 2015-04-02 17:40
Good for me to close with the latest one.

**Comment by cloudnautique** [comment] 2015-04-02 17:41
Thanks.

**Closed by cloudnautique** 2015-04-02 17:41 UTC
